id: I653292C0
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:15:38.788694
last_modified: 2023-02-08 15:15:38.788783
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: zh
bases:
  70EB:
    base_file: 70EB.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
